import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { io } from "socket.io-client";
import { signOut, useSession } from "next-auth/client";

import { connectToDatabase } from "../util/mongodb.js";

export default function Home() {
  const router = useRouter();
  const [session, loading] = useSession();
  const server_url = process.env.NEXT_PUBLIC_SERVER_URL;
  const socket = io(`${server_url}`);

  socket.on("connect", () => {
    console.log(socket.id, "id socket");
  });

  useEffect(() => {
    if (!(session || loading)) {
      router.push("/");
    }
  }, [session, loading]);

  if (!session || loading) {
    return <p>Loading...</p>;
  }

  return (
    <div>
      <Head>
        <title>Chat Skoot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {session ? (
        <>
          <p className="text-xl">Message Page</p>
          <p>{session.user?.name}</p>
          <p>{session.user?.email}</p>
          <button
            className="text-white bg-blue-500 p-2 mt-3"
            onClick={() => {
              signOut({ redirect: false });
            }}
          >
            Sign out
          </button>
        </>
      ) : null}
    </div>
  );
}

// export async function getStaticProps() {
//   const { db } = await connectToDatabase();
//   const movies = await db.collection("movies").find({}).limit(20).toArray();
//   console.log("db connected");

//   return {
//     props: { movies: JSON.parse(JSON.stringify(movies)) },
//   };
// }
